export const webp = Uint8Array.from(
  Buffer.from(
    'UklGRlQAAABXRUJQVlA4WAoAAAAQAAAAAQAAAgAAQUxQSAcAAAAAgICAgICAAFZQOCAmAAAAMAEAnQEqAgADAAFAJiWgAANwAP7xTS///MvP/+Zef/8y8/5iYAA=',
    'base64',
  ),
);
export const staticPng = Uint8Array.from(
  Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAAIAAAADCAYAAAC56t6BAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAEUlEQVR4nGP4wBDQAMIMGAwAkNsKgUfvz3YAAAAASUVORK5CYII=',
    'base64',
  ),
);
export const staticGif = Uint8Array.from(
  Buffer.from(
    'R0lGODlhAgADAIAAAExpcfAAUCH5BAUAAAAALAAAAAACAAMAAAICjF8AOw==',
    'base64',
  ),
);
export const jpeg = Uint8Array.from(
  Buffer.from(
    '/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAADAAIDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAf/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCFACgv/9k=',
    'base64',
  ),
);
