# Regras dos segmentos (fonte única: gera lib/segment-rules.ts no app; veja LEIA-ME.md).
# Um grupo casa um produto quando: (categoria está em `categories` OU o nome
# tem alguma palavra de `keywords`) E o nome não tem nenhuma de `exclude`.
# Palavras casam pelo INÍCIO da palavra ("sacola" pega "sacolas").

C = dict(
    FS='1.1-food service', MERC='1.2-mercearia', BISC='1.3-biscoitos', MASSAS='1.4-massas',
    COND='1.5-condimentos guarana', SANTA='1.6-santa amalia',
    BALAS='2.1-balas & drops', CHICL='2.2-chicletes', PIRUL='2.3-pirulitos', CHOC='2.4-chocolates',
    DOCESBR='2.5-doces / brinquedos', SALG='2.6-salgadinhos / pipocas / chips', GULO='2.7-gulozitos',
    SUCOS='3.1-sucos', REFRI='3.2-refrigerantes', ENERG='3.3-energeticos', AGUA='3.4-agua mineral',
    CERV='4.1-cervejas', DEST='4.2-destilados', VINHO='4.3-vinhos & espumantes',
    HIG='higiene pessoal', LIMP='limpeza', FILME='filme pvc/ papel aluminio', FOGOS='fogos', UTIL='utilidades',
    DESC='descartaveis', EPS='eps (isopor)/bandejas aluminio', POTES='potes redondo / retangular',
    SACOLAS='sacolas/ bobinas/ sacos pp',
    H_DARK='barra dark', H_REG='barra regular', H_MIX='hersheys mix', H_FS='linha foods service',
    ART_CHIPS='batata chips art fritas', ART_PALHA='palha art fritas', BANHAS='banhas', TORRESMOS='torresmos',
    Y_ALIM='alimentos', Y_FAR='farinhas & farofas', Y_PIP='pipocas microondas', Y_SALG='salgadinhos', Y_TEMP='temperos',
    DB='dona benta',
)
c = lambda *keys: [C[k] for k in keys]
# Panelas e afins têm "tampa" no nome ("frigideira s/ tampa"): nunca são descartáveis.
PANELAS = ['frigideira', 'panela', 'canecao', 'caneca', 'leiteira', 'cuscuzeira', 'chaleira',
           'caçarola', 'cacarola', 'forma de', 'isqueiro']
# "copo " com espaço: senão pega as marcas Copoplast e Copobras (pratos, bandejas...).

# Blocos reaproveitados entre segmentos
BEBIDAS_SEM_ALCOOL = dict(name='Bebidas', categories=c('SUCOS', 'REFRI', 'ENERG', 'AGUA'))
BEBIDAS_ALCOOL = dict(name='Cervejas, destilados e vinhos', categories=c('CERV', 'DEST', 'VINHO'),
                      exclude=['porta', 'cesta'])
BOMBONIERE = dict(name='Bomboniere', categories=c('BALAS', 'CHICL', 'PIRUL', 'CHOC', 'DOCESBR',
                                                   'H_DARK', 'H_REG', 'H_MIX'),
                  keywords=['geladinho', 'banana fit'], exclude=['chips', 'tortilla', 'salgadinho', 'pipoca'])
SALGADINHOS = dict(name='Salgadinhos e petiscos', categories=c('SALG', 'Y_SALG', 'Y_PIP', 'ART_CHIPS', 'TORRESMOS'),
                   keywords=['amendoim', 'pururuca', 'chips', 'tortilla', 'tortilha', 'salgadinho', 'pipoca'],
                   exclude=['mendoreto', 'coq', 'chocolate', 'colorido', 'doce', 'bala', 'barra', 'torroni',
                            'milho p/pipoca', 'sacola', 'sorvete'])
DESCARTAVEIS_MESA = dict(
    name='Descartáveis', keywords=['copo ', 'prato', 'garfo', 'colher', 'faca', 'talher', 'canudo', 'guardanapo',
                                   'mexedor', 'palito', 'tampa'],
    categories=c('DESC'), exclude=['doce', 'bala', 'choco', 'luva', 'mascara', 'touca', 'dispenser', 'extrato',
                                     'pilha', 'americano', 'nadir', 'porta', 'azeitona', 'agua', 'marmit', 'pote',
                                     'emb ', 'emb.', 'embalagem', 'garrafa', 'pazinha', 'suporte', 'sacola',
                                     'frangueira', 'termico', 'avental', *PANELAS])
SACHES = dict(name='Sachês e molhos individuais', keywords=['sache'],
              exclude=['canudo', 'garfo', 'faca', 'colher', 'sabao', 'amaciante', 'detergente', 'milho', 'ervilha'])
EPI = dict(name='Luvas, toucas e proteção', keywords=['luva', 'touca', 'mascara', 'avental'])
SACOLAS = dict(name='Sacolas e bobinas', categories=c('SACOLAS'),
               exclude=['teste', 'hambur', 'talher'])
LIMPEZA = dict(name='Limpeza', categories=c('LIMP'),
               keywords=['vassoura', 'rodo', 'pa p/ lixo', 'pa de lixo', 'esponja', 'pano', 'saco lixo',
                         'papel toalha', 'dispenser', 'escova sanit', 'desentupidor', 'balde', 'lixeira'])
FILME = dict(name='Filme PVC e papel alumínio', categories=c('FILME'))
MARMITEX = dict(name='Marmitex e bandejas', keywords=['marmitex', 'marmita', 'bandeja', 'assadeira', 'pote termico',
                                                      'copo termico', 'tampa pote'],
                categories=c('EPS'), exclude=['disco pizza', 'hambur', 'prato', *PANELAS])
POTES = dict(name='Potes, garrafas e tampas', keywords=['pote', 'emb kit pot', 'sushi', 'emb. ret', 'embalagem (base)',
                                                         'embalagem (tampa)', 'frangueira', 'garrafa quadrada',
                                                         'garrafa cristal'], categories=[],
             exclude=['choco', 'pacoca', 'doce', 'bala', 'goma', 'confeito', 'granulado', 'cond ', 'escova',
                      'soda', 'marmitex', 'termico', 'brinq', 'slime', 'chicle', 'pir '])

# --- Insumos food service (restaurantes, lanchonetes, marmitarias, pizzarias, hamburguerias) ---
# `min_size` em gramas/ml, lido do nome ("3,4KG", "900ML"). Sem tamanho no nome, só entra se
# tiver "bag"/"galão"/"balde". Confeitaria do Food Service fica de fora.
CONFEITARIA = ['corante', 'doce leite', 'doce de leite', 'bolinho', 'chantil', 'cobertura', 'granulado', 'confeit',
               'mistura p/ bolo', 'mistura bolo', 'creme de conf', 'sob.lactea', 'glucose', 'choco', 'gelatina',
               'aroma', 'essencia', 'leite po', 'recheio', 'forneavel', 'goiabada', 'coco ralado', 'fermento',
               'reforcador', 'melhorador', 'mist. prep']
NAO_INSUMO = ['sache', 'chips', 'pipoca', 'salg', 'bisc', 'bala', 'ag ', 'sab', 'sorvete', 'pote', 'doce', 'mini ']
FS_MOLHOS = dict(name='Molhos food service', min_size=700,
                 keywords=['maionese', 'catchup', 'mostarda', 'molho', 'barbecue', 'shoyu', 'extrato', 'polpa tomate',
                           'vinagre'],
                 exclude=[*NAO_INSUMO, *CONFEITARIA])
FS_CONDIMENTOS = dict(name='Temperos e condimentos', min_size=200, categories=c('COND', 'Y_TEMP'),
                      keywords=['caldo', 'tempero', 'cond ', 'sal refinado', 'sal grosso', 'amaciante de carne',
                                'creme de cebola', 'colorau', 'oregano', 'pimenta do reino', 'pimenta reino',
                                'alho frito'],
                      exclude=[*NAO_INSUMO, *CONFEITARIA, 'bicarbonato', 'sal amoniaco', 'caldo de cana'])
FS_OLEOS = dict(name='Óleos, gorduras e conservas', min_size=900, categories=c('BANHAS'),
                keywords=['oleo', 'azeite', 'banha', 'gordura', 'gordurina', 'margarina', 'azeitona', 'palmito',
                          'milho verde', 'ervilha', 'seleta', 'cogumelo', 'champignon', 'pepino', 'pimenta biquinho',
                          'tomate seco', 'cebolinha', 'alcaparra', 'atum', 'sardinha', 'conserva'],
                exclude=[*NAO_INSUMO, *CONFEITARIA])
FS_FARINHAS = dict(name='Farinhas, massas e grãos', min_size=900,
                   keywords=['far trigo', 'farinha', 'farofa', 'polvilho', 'fecula', 'amido', 'arroz', 'feijao',
                             'fuba', 'trigo para kibe', 'trigo p', 'batata palha', 'mist. prep. pao de queijo',
                             'macarrao', 'espaguete', 'massa', 'batata em flocos', 'pure'],
                   exclude=[*NAO_INSUMO, 'aveia', 'kimilho', 'mistura p/ bolo', 'mistura bolo', 'creme de conf',
                            'massa corrida'])
FS_INSUMOS = [FS_MOLHOS, FS_CONDIMENTOS, FS_OLEOS, FS_FARINHAS]

SEGMENTS = [
    dict(id='supermercados', name='Supermercados e mercearias', note='Revenda do dia a dia e abastecimento',
         icon='basket', groups=[
             dict(name='Mercearia', categories=c('MERC', 'MASSAS', 'SANTA', 'Y_ALIM', 'Y_FAR', 'Y_TEMP', 'COND',
                                                 'ART_PALHA', 'BANHAS'),
                  keywords=['batata palha', 'banha', 'cebolinha', 'pepino', 'palmito', 'trigo para kibe', 'tapioca',
                            'leite po', 'alho frito', 'batata em flocos'],
                  exclude=['cesta']),
             dict(name='Biscoitos e matinais', categories=c('BISC'), keywords=['achocolat', 'cafe radiante', 'cereal']),
             BEBIDAS_SEM_ALCOOL, BEBIDAS_ALCOOL, BOMBONIERE, SALGADINHOS,
             dict(name='Higiene e perfumaria', categories=c('HIG'), keywords=['papel hig', 'fralda']),
             LIMPEZA,
             dict(name='Sacolas e bobinas', categories=c('SACOLAS'), keywords=[],
                  exclude=['teste', 'hambur', 'talher', 'deliv', 'pizza']),
             dict(name='Utilidades e bazar', categories=c('UTIL', 'FILME'),
                  exclude=['vassoura', 'rodo', 'saco lixo', 'saco p/lixo', 'esponja', 'pano', 'porta latinha',
                           'porta cerveja', 'porta litrao', 'porta latao', 'porta guardanapo', 'escova sanit',
                           'esfregao', 'rastelo', 'cabo madeira', 'pa p/', 'pa para', 'pa s/cabo', 'pa (s/cabo)',
                           'p/lixo', 'flanela', 'papel toalha']),
             dict(name='Datas especiais', keywords=['cesta', 'panettone', 'chocotone', 'ovo de pascoa', 'caixa natal'],
                  categories=c('FOGOS')),
         ]),
    dict(id='restaurantes', name='Restaurantes e lanchonetes', note='Insumos, descartáveis e embalagens',
         icon='restaurant', groups=[
             *FS_INSUMOS,
             SACHES, DESCARTAVEIS_MESA, EPI, MARMITEX, POTES,
             dict(name='Sacolas para viagem', categories=c('SACOLAS'),
                  exclude=['teste', 'lixo', 'acougue', 'pipoca', 'chup', 'bobina pic']),
             dict(name='Bebidas para revenda', categories=c('SUCOS', 'REFRI', 'ENERG', 'AGUA', 'CERV'),
                  exclude=['porta', 'cesta']),
             dict(name='Cozinha e limpeza', categories=c('LIMP', 'FILME'),
                  keywords=['frigideira', 'canecao', 'panela', 'caneca', 'coador', 'escorredor', 'concha',
                            'escumadeira', 'tabua', 'taboa', 'pano', 'esponja', 'saco lixo', 'papel toalha',
                            'porta guardanapo', 'galheteiro', 'saleiro'],
                  exclude=['vinho']),
         ]),
    dict(id='padarias', name='Padarias e confeitarias', note='Produção, embalagens e revenda de balcão',
         icon='bread', groups=[
             dict(name='Farinhas, fermentos e misturas', categories=c('DB'),
                  keywords=['far trigo', 'farinha', 'fermento', 'fermix', 'mistura p/ bolo', 'mistura bolo',
                            'mistura p/bolo', 'mist. prep', 'mistura p/ pao', 'mistura p panif', 'panif', 'amido', 'polvilho', 'fuba', 'trigo p',
                            'melhorador', 'reforcador', 'cerelis', 'tapioca', 'fecula'],
                  exclude=['bisc polvilho', 'salg', 'kibe', 'mandioca', 'kimilho', 'aveia']),
             dict(name='Recheios, coberturas e confeitos', categories=c('H_FS'),
                  # "doce de leite (EBL)" é doce de balcão; "bicarbonato" e sachê de açúcar não são recheio
                  keywords=['margarina', 'chantil', 'cobertura', 'recheio', 'creme de conf', 'creme culinario',
                            'choc. granul', 'granulado', 'coco ralado', 'leite cond', 'leite condensado',
                            'acucar', 'gelatina sem sabor', 'gelatina em po', 'corante', 'confeit',
                            'sob.lactea', 'doce brigadeiro', 'doce famoso', 'doce palha', 'leite de coco',
                            'creme culinar', 'ovomaltine', 'pessego em calda', 'forneavel', 'choco creme', 'creme de leite',
                            'chocolate em po', 'choco em po', 'achocolatado em po', 'goiabada', 'essencia', 'aroma',
                            'doce leite', 'leite po',
                            'glucose', 'cremor', 'emulsificante'],
                  exclude=['bala', 'bisc', 'suco', 'goma', 'ref ', 'gomets', 'pirulito', 'pir ', 'chup ', 'doce mole',
                           'brinq', 'lavanda', 'limpadua', 'sequilho', 'amassyxup', 'bicarbonato', 'sache', 'catchup',
                           'zero acucar', 'doce goiabada', 'ebl', 'barrinha', 'barra']),
             dict(name='Embalagens de bolo, torta e doces',
                  keywords=['emb bolo', 'emba. bolo', 'embalagem p/ bolo', 'torta', 'leva doce', 'salgados/doces',
                            'emb leva', 'forminha', 'fatia', 'mini bolo', 'cake', 'cupcake', 'bandeja', 'disco',
                            'tampa'],
                  categories=[], exclude=['pizza', 'marmitex', 'copo', 'pote termico', 'eps', 'doce mole', 'isopor',
                                          'hambur', 'azeitona', 'cogumelo', 'fatiad', 'chicle', 'pir ', *PANELAS]),
             dict(name='Sacolas, sacos e papéis', categories=c('SACOLAS'),
                  keywords=['papel manteiga', 'papel canada', 'papel p/'],
                  exclude=['teste', 'lixo', 'hambur', 'pizza', 'cigarro', 'acougue', 'cachorro']),
             dict(name='Descartáveis e proteção',
                  keywords=['luva', 'touca', 'mascara', 'guardanapo', 'copo ', 'garfo', 'colher', 'mexedor',
                            'filme pvc', 'papel aluminio'],
                  exclude=['doce', 'bala', 'choco', 'extrato', 'americano', 'nadir', 'porta guardanapo',
                           'termico', 'borracha', 'latex', 'nitrilica', 'azeitona', 'agua']),
             dict(name='Frios e lanches', keywords=['mortadela', 'salsicha', 'linguica', 'linguiça', 'presunto',
                                                    'apresuntado', 'queijo prato', 'mussarela', 'salame'],
                  exclude=['chips', 'salg', 'bisc', 'gulao', 'gulossauros', 'pipoca']),
             dict(name='Café, açúcar e adoçantes', keywords=['cafe ', 'adocante', 'sache acucar', 'acucar cristal',
                                                             'acucar refinado'],
                  exclude=['bala', 'barra', 'chicle', 'coador', 'colher', 'mexedor', 'bisc']),
             dict(name='Revenda de balcão', categories=c('BISC', 'SUCOS', 'REFRI', 'AGUA', 'CHOC', 'H_REG',
                                                         'H_DARK', 'BALAS', 'CHICL', 'PIRUL'),
                  keywords=['panettone', 'chocotone', 'bolinho', 'sequilho', 'rosquinha', 'wafer', 'achocolatado',
                            'vitamina', 'leite cond.', 'doce de leite (ebl)', 'pacoca', 'bananada', 'mariola',
                            'doce mole', 'doce de leite', 'nutry'],
                  exclude=['cesta', 'achocolatado em po']),
             LIMPEZA,
         ]),
    dict(id='docerias', name='Docerias e bombonieres', note='Doces, chocolates e embalagens para doces',
         icon='candy', groups=[
             dict(name='Chocolates', categories=c('CHOC', 'H_DARK', 'H_REG', 'H_MIX'), exclude=['cesta']),
             dict(name='Balas, chicletes e pirulitos', categories=c('BALAS', 'CHICL', 'PIRUL')),
             dict(name='Doces e brinquedos', categories=c('DOCESBR'),
                  keywords=['pacoca', 'pe de moleque', 'doce mole', 'mariola', 'goiabada', 'bananada', 'cocada',
                            'geladinho', 'banana fit'],
                  exclude=['coquetel', 'chips', 'tortilla', 'salgadinho', 'pipoca', 'forneavel', 'cremosa']),
             SALGADINHOS,
             dict(name='Confeitaria', keywords=['granulado', 'confeit', 'cobertura', 'coco ralado', 'leite cond',
                                                'sob.lactea', 'brigadeiro', 'chocolate em po', 'corante',
                                                'forneavel', 'choco creme'],
                  categories=c('H_FS'), exclude=['bala', 'bombom', 'brinq', 'pir ', 'sequilho', 'amassyxup',
                                                 'tortuguita']),
             dict(name='Embalagens para doces', keywords=['leva doce', 'salgados/doces', 'emb bolo', 'emba. bolo',
                                                          'torta', 'forminha', 'saquinho', 'celofane'],
                  exclude=['pizza']),
         ]),
    dict(id='bares', name='Bares e conveniências', note='Bebidas, petiscos e itens de balcão',
         icon='beer', groups=[
             dict(name='Cervejas', categories=c('CERV'), exclude=['porta']),
             dict(name='Destilados', categories=c('DEST'), exclude=['cesta']),
             dict(name='Vinhos e espumantes', categories=c('VINHO'), exclude=['cesta']),
             dict(name='Refrigerantes, sucos e energéticos', categories=c('REFRI', 'SUCOS', 'ENERG', 'AGUA')),
             SALGADINHOS,
             dict(name='Porções e petiscos', keywords=['azeitona', 'pepino', 'pepininho', 'cebolinha', 'calabresa',
                                                       'linguica', 'linguiça', 'mortadela', 'tremoco',
                                                       'ovo de codorna'],
                  exclude=['chips', 'doce', 'chocolate', 'bala', 'cond ']),
             dict(name='Bomboniere de balcão', categories=c('CHICL', 'BALAS', 'PIRUL', 'CHOC', 'H_REG', 'H_MIX')),
             dict(name='Copos, porta-latas e acessórios',
                  keywords=['porta latinha', 'porta cerveja', 'porta litrao', 'porta latao', 'copo americano',
                            'copo desc', 'copo transp', 'palito', 'canudo', 'guardanapo', 'porta guardanapo',
                            'porta canudo', 'baralho', 'abridor', 'isqueiro', 'gelo'],
                  exclude=['doce', 'pilha', 'bala']),
         ]),
    dict(id='delivery', name='Delivery e embalagens', note='Embalagens para preparo, entrega e viagem',
         icon='package', groups=[
             MARMITEX, POTES,
             dict(name='Pizza', keywords=['pizza', 'disco pizza'], exclude=['far trigo', 'molho']),
             dict(name='Hambúrguer e lanches', keywords=['hambur', 'hot dog', 'papel p/hamburg', 'embalagem batata',
                                                         'emb batata', 'papel acoplado'],
                  exclude=['molho']),
             dict(name='Sacolas de entrega', keywords=['deliv', 'kraft', 'sacola papel', 'sacola camis',
                                                       'sacola p/', 'sacola cam'],
                  exclude=['talher', 'teste', 'pipoca', 'chup']),
             dict(name='Copos e tampas', keywords=['copo ', 'tampa copo', 'tampa t', 'tampa bolha', 'tampa p/ copo'],
                  exclude=['doce', 'bala', 'choco', 'extrato', 'americano', 'nadir', 'pote', 'marmitex',
                           'termico', 'azeitona', 'agua', *PANELAS]),
             SACHES,
             dict(name='Talheres e guardanapos', keywords=['garfo', 'faca', 'colher', 'talher', 'guardanapo',
                                                           'canudo', 'mexedor'],
                  exclude=['porta']),
             FILME,
         ]),
    dict(id='higiene', name='Perfumarias e higiene', note='Higiene pessoal e cuidados',
         icon='sparkles', groups=[
             dict(name='Higiene pessoal', categories=c('HIG'),
                  exclude=['papel hig', 'fralda', 'creme dental', 'escova dental', 'escova dent', 'fio dental',
                           'enxaguante', 'lava roupas', 'limp. perf', 'papel interf', 'papel toalha', 'escolva']),
             dict(name='Papel higiênico e fraldas', keywords=['papel hig', 'fralda', 'lenco umedec']),
             dict(name='Higiene bucal', keywords=['creme dental', 'escova dental', 'escova dent', 'escolva', 'fio dental',
                                                  'enxaguante']),
         ]),
    dict(id='limpeza', name='Limpeza profissional', note='Produtos e utensílios de limpeza',
         icon='spray', groups=[
             dict(name='Produtos de limpeza', categories=c('LIMP'), keywords=['lava roupas', 'limp. perf'],
                  exclude=['vassoura', 'rodo', 'pano', 'esponja', 'luva', 'saco lixo']),
             dict(name='Vassouras, rodos e utensílios',
                  keywords=['vassoura', 'rodo', 'rastelo', 'pa p/', 'pa para', 'pa s/cabo', 'pa (s/cabo)', 'pa de lixo',
                            'cabo madeira',
                            'escova', 'saco p/lixo',
                            'desentupidor', 'balde', 'lixeira', 'esfregao', 'mop'],
                  exclude=['escova dental', 'escova dent']),
             dict(name='Panos, esponjas e luvas', keywords=['pano', 'esponja', 'flanela', 'luva', 'la de aco', 'bombril'],
                  exclude=['nitrilica', 'vinil', 'descartavel', 'latex', 'plast']),
             dict(name='Sacos de lixo', keywords=['saco lixo', 'saco de lixo']),
             dict(name='Papel toalha e dispensers', keywords=['papel toalha', 'papel interf', 'dispenser', 'papel hig']),
         ]),
    dict(id='utilidades', name='Utilidades e bazar', note='Utensílios e itens para o dia a dia',
         icon='grid', groups=[
             dict(name='Utilidades domésticas', categories=c('UTIL'),
                  exclude=['vassoura', 'rodo', 'rastelo', 'saco lixo', 'saco p/lixo', 'esponja', 'pano', 'pa p/',
                           'pa para', 'pa s/cabo', 'pa (s/cabo)', 'p/lixo', 'cabo madeira', 'papel toalha', 'escova',
                           'esfregao', 'flanela']),
             FILME,
             dict(name='Fogos e festas', categories=c('FOGOS'), keywords=['vela', 'balao']),
         ]),
    # --- Novos segmentos ---
    dict(id='pizzarias', name='Pizzarias', note='Massa, recheios, embalagens e bebidas',
         icon='pizza', groups=[
             dict(name='Massa: farinhas e fermentos', min_size=450,
                  keywords=['far trigo', 'fermento', 'fermix', 'farinha rosca', 'semolina', 'fuba'],
                  categories=c('DB'), exclude=['c/ferm', 'bolo']),
             dict(name='Molhos e recheios', min_size=900,
                  keywords=['molho tomate', 'molho de tomate', 'molho pizza', 'ajuda pizza', 'extrato',
                            'polpa tomate',
                                                      'azeitona', 'palmito', 'milho verde', 'ervilha', 'cogumelo',
                                                      'oregano', 'azeite', 'calabresa', 'mortadela', 'bacon',
                                                      'catupiry', 'requeijao', 'presunto', 'atum', 'sardinha'],
                  exclude=['chips', 'salg', 'pipoca', 'gulao', 'gulossauros', 'sache', 'farofa', 'sorvete', 'bisc']),
             FS_CONDIMENTOS,
             dict(name='Embalagens de pizza', keywords=['pizza', 'disco pizza', 'sacola p/pizza'],
                  exclude=['far trigo', 'molho']),
             SACHES,
             dict(name='Bebidas', categories=c('REFRI', 'SUCOS', 'AGUA', 'CERV'), exclude=['porta']),
             dict(name='Descartáveis e proteção',
                  keywords=['guardanapo', 'luva', 'touca', 'garfo', 'faca', 'papel aluminio'],
                  exclude=['porta guardanapo']),
         ]),
    dict(id='hamburguerias', name='Hamburguerias e lanches', note='Molhos, embalagens e descartáveis',
         icon='fast-food', groups=[
             dict(name='Molhos food service', min_size=900,
                  keywords=['maionese', 'catchup', 'mostarda', 'barbecue', 'molho cheddar', 'molho especial',
                            'molho verde', 'molho alho', 'molho hot dog', 'molho barbecue', 'molho shoyo',
                            'molho pimenta'],
                  exclude=['sache', 'pote']),
             SACHES,
             dict(name='Batata, bacon e acompanhamentos', min_size=900,
                  keywords=['batata palha', 'bacon', 'salsicha', 'banha', 'torresmo', 'cheddar',
                            'milho verde', 'ervilha'],
                  categories=c('BANHAS'),
                  exclude=['chips', 'gulao', 'gulossauros', 'pipoca', 'doce', 'farofa', 'sache', 'sorvete', 'salg',
                           ' ond ', 'molho']),
             dict(name='Embalagens de lanche', keywords=['hambur', 'hot dog', 'papel p/hamburg', 'emb batata',
                                                         'embalagem batata', 'sacola p/hamburg', 'papel acoplado'],
                  exclude=['molho']),
             dict(name='Sacolas de entrega', keywords=['deliv', 'kraft', 'sacola papel'], exclude=['talher']),
             dict(name='Bebidas', categories=c('REFRI', 'SUCOS', 'ENERG', 'AGUA', 'CERV'), exclude=['porta']),
             dict(name='Descartáveis e proteção', keywords=['guardanapo', 'canudo', 'copo desc', 'copo transp',
                                                            'luva', 'touca', 'garfo', 'faca'],
                  exclude=['porta', 'borracha', 'latex']),
         ]),
    dict(id='sorveterias', name='Sorveterias e açaiterias', note='Bases, coberturas, copos e colheres',
         icon='ice-cream', groups=[
             dict(name='Bases e pós para sorvete', keywords=['po  p/sorvete', 'po p/sorvete', 'sorvete', 'acai',
                                                             'liga neutra', 'emulsificante', 'saborizante'],
                  exclude=['doce mole', 'banana fit', 'mariola', 'ref ', 'pazinha', 'colher']),
             dict(name='Coberturas e complementos',
                  keywords=['cobertura', 'granulado', 'confeit', 'leite cond', 'leite condensado', 'pacoca',
                            'amendoim', 'choco creme', 'creme de avela', 'coco ralado', 'calda', 'sob.lactea',
                            'marshmallow', 'chocoball', 'choco bolinha', 'ovomaltine', 'gotas'],
                  exclude=['bala', 'mendoreto', 'dori 70g', 'pirulito', 'pir ', 'japones', 'salgado', 'coquetel',
                           'amassyxup', 'barra', 'barrinha', 'brinq', 'sequilho', 'doce machado', 'bisc']),
             dict(name='Copos, potes e tampas', keywords=['copo ', 'pote', 'tampa copo', 'tampa bolha', 'tampa t',
                                                          'tampa pote'],
                  exclude=['doce', 'bala', 'choco', 'pacoca', 'extrato', 'americano', 'nadir', 'marmitex',
                           'emb kit', 'goma', 'confeito', 'cond ', 'soda', 'escova', 'sushi', 'p/ molho',
                           'azeitona', 'agua', 'brinq', 'slime', 'chicle', 'pir ', *PANELAS]),
             dict(name='Colheres, canudos e guardanapos', keywords=['colher', 'canudo', 'guardanapo', 'mexedor',
                                                                    'pazinha'],
                  exclude=['porta']),
             dict(name='Bebidas', categories=c('REFRI', 'SUCOS', 'AGUA')),
         ]),
    dict(id='marmitarias', name='Marmitarias e restaurantes a quilo', note='Cozinha em volume e embalagens',
         icon='restaurant', groups=[
             *FS_INSUMOS,
             MARMITEX,
             dict(name='Filme e papel alumínio', categories=c('FILME')),
             SACHES,
             dict(name='Talheres e descartáveis', keywords=['garfo', 'faca', 'colher', 'talher', 'guardanapo',
                                                            'copo desc', 'copo transp'],
                  exclude=['porta']),
             dict(name='Sacolas', keywords=['sacola camis', 'sacola cam', 'sacola p/', 'deliv', 'kraft'],
                  exclude=['teste', 'hambur', 'pipoca', 'chup']),
             dict(name='Bebidas', categories=c('REFRI', 'SUCOS', 'AGUA')),
             EPI,
         ]),
    # --- Coleções de data (hidden=True: não aparecem na aba Segmentos; abrem
    # pelo atalho do tema, ex.: "Natal" na Início) ---
    dict(id='natal', name='Especial de Natal', note='Produtos para a ceia, presentes e festas', icon='tree',
         hidden=True, groups=[
             dict(name='Panetones e chocotones', keywords=['panettone', 'panetone', 'chocotone']),
             dict(name='Cestas natalinas', keywords=['cesta natalina', 'cesta 0'], exclude=['garrafa', 'litrao']),
             dict(name='Bombons e chocolates para presente', keywords=['bombom', 'trufa', 'caixa de bombom'],
                  exclude=['bala']),
             dict(name='Bebidas para as festas', keywords=['espumante', 'sidra', 'vinho', 'suco de uva', 'suco uva',
                                                           'champagne', 'frisante'],
                  exclude=['porta', 'cesta']),
             dict(name='Caixas e embalagens de presente', keywords=['caixa natal', 'presente', 'embalagem presente']),
         ]),
]
