import type { AppIconName } from '@/components/AppIcon';

/**
 * Segmentos de clientes do app. ARQUIVO GERADO: edite
 * `scripts/segmentos/segrules.py` e rode `gen.py` (veja o LEIA-ME.md de lá),
 * que também confere as regras contra o catálogo publicado.
 *
 * Diferente do site, um produto pode estar em VÁRIOS segmentos: a sacola
 * serve para a padaria, o restaurante e o delivery. Cada segmento é dividido
 * em grupos (insumos, embalagens, revenda...).
 *
 * Um grupo inclui o produto quando a CATEGORIA dele está em `categories` OU o
 * NOME tem alguma palavra de `keywords`, e o nome não tem nenhuma de
 * `exclude`. As palavras casam pelo início ("sacola" pega "sacolas"); um
 * espaço no fim exige a palavra inteira ("copo " não pega "Copobras").
 * Acentos e maiúsculas são ignorados.
 *
 * `minSize` (gramas ou ml, 0 = sem limite) exige embalagem grande, lida do
 * nome ("3,4KG", "900ML", "5,01 LTS"): é o que separa o insumo food service
 * (balde, galão, saco de 25 kg) do item de prateleira. Sem tamanho no nome, o
 * produto só entra se tiver "bag", "galão", "balde" ou "(GR)".
 */

export type SegmentGroupRule = {
  name: string;
  categories: string[];
  keywords: string[];
  exclude: string[];
  minSize: number;
};

export type SegmentRule = {
  id: string;
  name: string;
  note: string;
  icon: AppIconName;
  groups: SegmentGroupRule[];
};

export const SEGMENT_RULES: SegmentRule[] = [
  {
    id: 'supermercados',
    name: 'Supermercados e mercearias',
    note: 'Revenda do dia a dia e abastecimento',
    icon: 'basket',
    groups: [
      {
        name: 'Mercearia',
        categories: ['1.2-mercearia', '1.4-massas', '1.6-santa amalia', 'alimentos', 'farinhas & farofas', 'temperos', '1.5-condimentos guarana', 'palha art fritas', 'banhas'],
        keywords: ['batata palha', 'banha', 'cebolinha', 'pepino', 'palmito', 'trigo para kibe', 'tapioca', 'leite po', 'alho frito', 'batata em flocos'],
        exclude: ['cesta'],
        minSize: 0,
      },
      {
        name: 'Biscoitos e matinais',
        categories: ['1.3-biscoitos'],
        keywords: ['achocolat', 'cafe radiante', 'cereal'],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Bebidas',
        categories: ['3.1-sucos', '3.2-refrigerantes', '3.3-energeticos', '3.4-agua mineral'],
        keywords: [],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Cervejas, destilados e vinhos',
        categories: ['4.1-cervejas', '4.2-destilados', '4.3-vinhos & espumantes'],
        keywords: [],
        exclude: ['porta', 'cesta'],
        minSize: 0,
      },
      {
        name: 'Bomboniere',
        categories: ['2.1-balas & drops', '2.2-chicletes', '2.3-pirulitos', '2.4-chocolates', '2.5-doces / brinquedos', 'barra dark', 'barra regular', 'hersheys mix'],
        keywords: ['geladinho', 'banana fit'],
        exclude: ['chips', 'tortilla', 'salgadinho', 'pipoca'],
        minSize: 0,
      },
      {
        name: 'Salgadinhos e petiscos',
        categories: ['2.6-salgadinhos / pipocas / chips', 'salgadinhos', 'pipocas microondas', 'batata chips art fritas', 'torresmos'],
        keywords: ['amendoim', 'pururuca', 'chips', 'tortilla', 'tortilha', 'salgadinho', 'pipoca'],
        exclude: ['mendoreto', 'coq', 'chocolate', 'colorido', 'doce', 'bala', 'barra', 'torroni', 'milho p/pipoca', 'sacola', 'sorvete'],
        minSize: 0,
      },
      {
        name: 'Higiene e perfumaria',
        categories: ['higiene pessoal'],
        keywords: ['papel hig', 'fralda'],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Limpeza',
        categories: ['limpeza'],
        keywords: ['vassoura', 'rodo', 'pa p/ lixo', 'pa de lixo', 'esponja', 'pano', 'saco lixo', 'papel toalha', 'dispenser', 'escova sanit', 'desentupidor', 'balde', 'lixeira'],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Sacolas e bobinas',
        categories: ['sacolas/ bobinas/ sacos pp'],
        keywords: [],
        exclude: ['teste', 'hambur', 'talher', 'deliv', 'pizza'],
        minSize: 0,
      },
      {
        name: 'Utilidades e bazar',
        categories: ['utilidades', 'filme pvc/ papel aluminio'],
        keywords: [],
        exclude: ['vassoura', 'rodo', 'saco lixo', 'saco p/lixo', 'esponja', 'pano', 'porta latinha', 'porta cerveja', 'porta litrao', 'porta latao', 'porta guardanapo', 'escova sanit', 'esfregao', 'rastelo', 'cabo madeira', 'pa p/', 'pa para', 'pa s/cabo', 'pa (s/cabo)', 'p/lixo', 'flanela', 'papel toalha'],
        minSize: 0,
      },
      {
        name: 'Datas especiais',
        categories: ['fogos'],
        keywords: ['cesta', 'panettone', 'chocotone', 'ovo de pascoa', 'caixa natal'],
        exclude: [],
        minSize: 0,
      },
    ],
  },
  {
    id: 'restaurantes',
    name: 'Restaurantes e lanchonetes',
    note: 'Insumos, descartáveis e embalagens',
    icon: 'restaurant',
    groups: [
      {
        name: 'Molhos food service',
        categories: [],
        keywords: ['maionese', 'catchup', 'mostarda', 'molho', 'barbecue', 'shoyu', 'extrato', 'polpa tomate', 'vinagre'],
        exclude: ['sache', 'chips', 'pipoca', 'salg', 'bisc', 'bala', 'ag ', 'sab', 'sorvete', 'pote', 'doce', 'mini ', 'corante', 'doce leite', 'doce de leite', 'bolinho', 'chantil', 'cobertura', 'granulado', 'confeit', 'mistura p/ bolo', 'mistura bolo', 'creme de conf', 'sob.lactea', 'glucose', 'choco', 'gelatina', 'aroma', 'essencia', 'leite po', 'recheio', 'forneavel', 'goiabada', 'coco ralado', 'fermento', 'reforcador', 'melhorador', 'mist. prep'],
        minSize: 700,
      },
      {
        name: 'Temperos e condimentos',
        categories: ['1.5-condimentos guarana', 'temperos'],
        keywords: ['caldo', 'tempero', 'cond ', 'sal refinado', 'sal grosso', 'amaciante de carne', 'creme de cebola', 'colorau', 'oregano', 'pimenta do reino', 'pimenta reino', 'alho frito'],
        exclude: ['sache', 'chips', 'pipoca', 'salg', 'bisc', 'bala', 'ag ', 'sab', 'sorvete', 'pote', 'doce', 'mini ', 'corante', 'doce leite', 'doce de leite', 'bolinho', 'chantil', 'cobertura', 'granulado', 'confeit', 'mistura p/ bolo', 'mistura bolo', 'creme de conf', 'sob.lactea', 'glucose', 'choco', 'gelatina', 'aroma', 'essencia', 'leite po', 'recheio', 'forneavel', 'goiabada', 'coco ralado', 'fermento', 'reforcador', 'melhorador', 'mist. prep', 'bicarbonato', 'sal amoniaco', 'caldo de cana'],
        minSize: 200,
      },
      {
        name: 'Óleos, gorduras e conservas',
        categories: ['banhas'],
        keywords: ['oleo', 'azeite', 'banha', 'gordura', 'gordurina', 'margarina', 'azeitona', 'palmito', 'milho verde', 'ervilha', 'seleta', 'cogumelo', 'champignon', 'pepino', 'pimenta biquinho', 'tomate seco', 'cebolinha', 'alcaparra', 'atum', 'sardinha', 'conserva'],
        exclude: ['sache', 'chips', 'pipoca', 'salg', 'bisc', 'bala', 'ag ', 'sab', 'sorvete', 'pote', 'doce', 'mini ', 'corante', 'doce leite', 'doce de leite', 'bolinho', 'chantil', 'cobertura', 'granulado', 'confeit', 'mistura p/ bolo', 'mistura bolo', 'creme de conf', 'sob.lactea', 'glucose', 'choco', 'gelatina', 'aroma', 'essencia', 'leite po', 'recheio', 'forneavel', 'goiabada', 'coco ralado', 'fermento', 'reforcador', 'melhorador', 'mist. prep'],
        minSize: 900,
      },
      {
        name: 'Farinhas, massas e grãos',
        categories: [],
        keywords: ['far trigo', 'farinha', 'farofa', 'polvilho', 'fecula', 'amido', 'arroz', 'feijao', 'fuba', 'trigo para kibe', 'trigo p', 'batata palha', 'mist. prep. pao de queijo', 'macarrao', 'espaguete', 'massa', 'batata em flocos', 'pure'],
        exclude: ['sache', 'chips', 'pipoca', 'salg', 'bisc', 'bala', 'ag ', 'sab', 'sorvete', 'pote', 'doce', 'mini ', 'aveia', 'kimilho', 'mistura p/ bolo', 'mistura bolo', 'creme de conf', 'massa corrida'],
        minSize: 900,
      },
      {
        name: 'Sachês e molhos individuais',
        categories: [],
        keywords: ['sache'],
        exclude: ['canudo', 'garfo', 'faca', 'colher', 'sabao', 'amaciante', 'detergente', 'milho', 'ervilha'],
        minSize: 0,
      },
      {
        name: 'Descartáveis',
        categories: ['descartaveis'],
        keywords: ['copo ', 'prato', 'garfo', 'colher', 'faca', 'talher', 'canudo', 'guardanapo', 'mexedor', 'palito', 'tampa'],
        exclude: ['doce', 'bala', 'choco', 'luva', 'mascara', 'touca', 'dispenser', 'extrato', 'pilha', 'americano', 'nadir', 'porta', 'azeitona', 'agua', 'marmit', 'pote', 'emb ', 'emb.', 'embalagem', 'garrafa', 'pazinha', 'suporte', 'sacola', 'frangueira', 'termico', 'avental', 'frigideira', 'panela', 'canecao', 'caneca', 'leiteira', 'cuscuzeira', 'chaleira', 'caçarola', 'cacarola', 'forma de', 'isqueiro'],
        minSize: 0,
      },
      {
        name: 'Luvas, toucas e proteção',
        categories: [],
        keywords: ['luva', 'touca', 'mascara', 'avental'],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Marmitex e bandejas',
        categories: ['eps (isopor)/bandejas aluminio'],
        keywords: ['marmitex', 'marmita', 'bandeja', 'assadeira', 'pote termico', 'copo termico', 'tampa pote'],
        exclude: ['disco pizza', 'hambur', 'prato', 'frigideira', 'panela', 'canecao', 'caneca', 'leiteira', 'cuscuzeira', 'chaleira', 'caçarola', 'cacarola', 'forma de', 'isqueiro'],
        minSize: 0,
      },
      {
        name: 'Potes, garrafas e tampas',
        categories: [],
        keywords: ['pote', 'emb kit pot', 'sushi', 'emb. ret', 'embalagem (base)', 'embalagem (tampa)', 'frangueira', 'garrafa quadrada', 'garrafa cristal'],
        exclude: ['choco', 'pacoca', 'doce', 'bala', 'goma', 'confeito', 'granulado', 'cond ', 'escova', 'soda', 'marmitex', 'termico', 'brinq', 'slime', 'chicle', 'pir '],
        minSize: 0,
      },
      {
        name: 'Sacolas para viagem',
        categories: ['sacolas/ bobinas/ sacos pp'],
        keywords: [],
        exclude: ['teste', 'lixo', 'acougue', 'pipoca', 'chup', 'bobina pic'],
        minSize: 0,
      },
      {
        name: 'Bebidas para revenda',
        categories: ['3.1-sucos', '3.2-refrigerantes', '3.3-energeticos', '3.4-agua mineral', '4.1-cervejas'],
        keywords: [],
        exclude: ['porta', 'cesta'],
        minSize: 0,
      },
      {
        name: 'Cozinha e limpeza',
        categories: ['limpeza', 'filme pvc/ papel aluminio'],
        keywords: ['frigideira', 'canecao', 'panela', 'caneca', 'coador', 'escorredor', 'concha', 'escumadeira', 'tabua', 'taboa', 'pano', 'esponja', 'saco lixo', 'papel toalha', 'porta guardanapo', 'galheteiro', 'saleiro'],
        exclude: ['vinho'],
        minSize: 0,
      },
    ],
  },
  {
    id: 'padarias',
    name: 'Padarias e confeitarias',
    note: 'Produção, embalagens e revenda de balcão',
    icon: 'bread',
    groups: [
      {
        name: 'Farinhas, fermentos e misturas',
        categories: ['dona benta'],
        keywords: ['far trigo', 'farinha', 'fermento', 'fermix', 'mistura p/ bolo', 'mistura bolo', 'mistura p/bolo', 'mist. prep', 'mistura p/ pao', 'mistura p panif', 'panif', 'amido', 'polvilho', 'fuba', 'trigo p', 'melhorador', 'reforcador', 'cerelis', 'tapioca', 'fecula'],
        exclude: ['bisc polvilho', 'salg', 'kibe', 'mandioca', 'kimilho', 'aveia'],
        minSize: 0,
      },
      {
        name: 'Recheios, coberturas e confeitos',
        categories: ['linha foods service'],
        keywords: ['margarina', 'chantil', 'cobertura', 'recheio', 'creme de conf', 'creme culinario', 'choc. granul', 'granulado', 'coco ralado', 'leite cond', 'leite condensado', 'acucar', 'gelatina sem sabor', 'gelatina em po', 'corante', 'confeit', 'sob.lactea', 'doce brigadeiro', 'doce famoso', 'doce palha', 'leite de coco', 'creme culinar', 'ovomaltine', 'pessego em calda', 'forneavel', 'choco creme', 'creme de leite', 'chocolate em po', 'choco em po', 'achocolatado em po', 'goiabada', 'essencia', 'aroma', 'doce leite', 'leite po', 'glucose', 'cremor', 'emulsificante'],
        exclude: ['bala', 'bisc', 'suco', 'goma', 'ref ', 'gomets', 'pirulito', 'pir ', 'chup ', 'doce mole', 'brinq', 'lavanda', 'limpadua', 'sequilho', 'amassyxup', 'bicarbonato', 'sache', 'catchup', 'zero acucar', 'doce goiabada', 'ebl', 'barrinha', 'barra'],
        minSize: 0,
      },
      {
        name: 'Embalagens de bolo, torta e doces',
        categories: [],
        keywords: ['emb bolo', 'emba. bolo', 'embalagem p/ bolo', 'torta', 'leva doce', 'salgados/doces', 'emb leva', 'forminha', 'fatia', 'mini bolo', 'cake', 'cupcake', 'bandeja', 'disco', 'tampa'],
        exclude: ['pizza', 'marmitex', 'copo', 'pote termico', 'eps', 'doce mole', 'isopor', 'hambur', 'azeitona', 'cogumelo', 'fatiad', 'chicle', 'pir ', 'frigideira', 'panela', 'canecao', 'caneca', 'leiteira', 'cuscuzeira', 'chaleira', 'caçarola', 'cacarola', 'forma de', 'isqueiro'],
        minSize: 0,
      },
      {
        name: 'Sacolas, sacos e papéis',
        categories: ['sacolas/ bobinas/ sacos pp'],
        keywords: ['papel manteiga', 'papel canada', 'papel p/'],
        exclude: ['teste', 'lixo', 'hambur', 'pizza', 'cigarro', 'acougue', 'cachorro'],
        minSize: 0,
      },
      {
        name: 'Descartáveis e proteção',
        categories: [],
        keywords: ['luva', 'touca', 'mascara', 'guardanapo', 'copo ', 'garfo', 'colher', 'mexedor', 'filme pvc', 'papel aluminio'],
        exclude: ['doce', 'bala', 'choco', 'extrato', 'americano', 'nadir', 'porta guardanapo', 'termico', 'borracha', 'latex', 'nitrilica', 'azeitona', 'agua'],
        minSize: 0,
      },
      {
        name: 'Frios e lanches',
        categories: [],
        keywords: ['mortadela', 'salsicha', 'linguica', 'linguiça', 'presunto', 'apresuntado', 'queijo prato', 'mussarela', 'salame'],
        exclude: ['chips', 'salg', 'bisc', 'gulao', 'gulossauros', 'pipoca'],
        minSize: 0,
      },
      {
        name: 'Café, açúcar e adoçantes',
        categories: [],
        keywords: ['cafe ', 'adocante', 'sache acucar', 'acucar cristal', 'acucar refinado'],
        exclude: ['bala', 'barra', 'chicle', 'coador', 'colher', 'mexedor', 'bisc'],
        minSize: 0,
      },
      {
        name: 'Revenda de balcão',
        categories: ['1.3-biscoitos', '3.1-sucos', '3.2-refrigerantes', '3.4-agua mineral', '2.4-chocolates', 'barra regular', 'barra dark', '2.1-balas & drops', '2.2-chicletes', '2.3-pirulitos'],
        keywords: ['panettone', 'chocotone', 'bolinho', 'sequilho', 'rosquinha', 'wafer', 'achocolatado', 'vitamina', 'leite cond.', 'doce de leite (ebl)', 'pacoca', 'bananada', 'mariola', 'doce mole', 'doce de leite', 'nutry'],
        exclude: ['cesta', 'achocolatado em po'],
        minSize: 0,
      },
      {
        name: 'Limpeza',
        categories: ['limpeza'],
        keywords: ['vassoura', 'rodo', 'pa p/ lixo', 'pa de lixo', 'esponja', 'pano', 'saco lixo', 'papel toalha', 'dispenser', 'escova sanit', 'desentupidor', 'balde', 'lixeira'],
        exclude: [],
        minSize: 0,
      },
    ],
  },
  {
    id: 'docerias',
    name: 'Docerias e bombonieres',
    note: 'Doces, chocolates e embalagens para doces',
    icon: 'candy',
    groups: [
      {
        name: 'Chocolates',
        categories: ['2.4-chocolates', 'barra dark', 'barra regular', 'hersheys mix'],
        keywords: [],
        exclude: ['cesta'],
        minSize: 0,
      },
      {
        name: 'Balas, chicletes e pirulitos',
        categories: ['2.1-balas & drops', '2.2-chicletes', '2.3-pirulitos'],
        keywords: [],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Doces e brinquedos',
        categories: ['2.5-doces / brinquedos'],
        keywords: ['pacoca', 'pe de moleque', 'doce mole', 'mariola', 'goiabada', 'bananada', 'cocada', 'geladinho', 'banana fit'],
        exclude: ['coquetel', 'chips', 'tortilla', 'salgadinho', 'pipoca', 'forneavel', 'cremosa'],
        minSize: 0,
      },
      {
        name: 'Salgadinhos e petiscos',
        categories: ['2.6-salgadinhos / pipocas / chips', 'salgadinhos', 'pipocas microondas', 'batata chips art fritas', 'torresmos'],
        keywords: ['amendoim', 'pururuca', 'chips', 'tortilla', 'tortilha', 'salgadinho', 'pipoca'],
        exclude: ['mendoreto', 'coq', 'chocolate', 'colorido', 'doce', 'bala', 'barra', 'torroni', 'milho p/pipoca', 'sacola', 'sorvete'],
        minSize: 0,
      },
      {
        name: 'Confeitaria',
        categories: ['linha foods service'],
        keywords: ['granulado', 'confeit', 'cobertura', 'coco ralado', 'leite cond', 'sob.lactea', 'brigadeiro', 'chocolate em po', 'corante', 'forneavel', 'choco creme'],
        exclude: ['bala', 'bombom', 'brinq', 'pir ', 'sequilho', 'amassyxup', 'tortuguita'],
        minSize: 0,
      },
      {
        name: 'Embalagens para doces',
        categories: [],
        keywords: ['leva doce', 'salgados/doces', 'emb bolo', 'emba. bolo', 'torta', 'forminha', 'saquinho', 'celofane'],
        exclude: ['pizza'],
        minSize: 0,
      },
    ],
  },
  {
    id: 'bares',
    name: 'Bares e conveniências',
    note: 'Bebidas, petiscos e itens de balcão',
    icon: 'beer',
    groups: [
      {
        name: 'Cervejas',
        categories: ['4.1-cervejas'],
        keywords: [],
        exclude: ['porta'],
        minSize: 0,
      },
      {
        name: 'Destilados',
        categories: ['4.2-destilados'],
        keywords: [],
        exclude: ['cesta'],
        minSize: 0,
      },
      {
        name: 'Vinhos e espumantes',
        categories: ['4.3-vinhos & espumantes'],
        keywords: [],
        exclude: ['cesta'],
        minSize: 0,
      },
      {
        name: 'Refrigerantes, sucos e energéticos',
        categories: ['3.2-refrigerantes', '3.1-sucos', '3.3-energeticos', '3.4-agua mineral'],
        keywords: [],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Salgadinhos e petiscos',
        categories: ['2.6-salgadinhos / pipocas / chips', 'salgadinhos', 'pipocas microondas', 'batata chips art fritas', 'torresmos'],
        keywords: ['amendoim', 'pururuca', 'chips', 'tortilla', 'tortilha', 'salgadinho', 'pipoca'],
        exclude: ['mendoreto', 'coq', 'chocolate', 'colorido', 'doce', 'bala', 'barra', 'torroni', 'milho p/pipoca', 'sacola', 'sorvete'],
        minSize: 0,
      },
      {
        name: 'Porções e petiscos',
        categories: [],
        keywords: ['azeitona', 'pepino', 'pepininho', 'cebolinha', 'calabresa', 'linguica', 'linguiça', 'mortadela', 'tremoco', 'ovo de codorna'],
        exclude: ['chips', 'doce', 'chocolate', 'bala', 'cond '],
        minSize: 0,
      },
      {
        name: 'Bomboniere de balcão',
        categories: ['2.2-chicletes', '2.1-balas & drops', '2.3-pirulitos', '2.4-chocolates', 'barra regular', 'hersheys mix'],
        keywords: [],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Copos, porta-latas e acessórios',
        categories: [],
        keywords: ['porta latinha', 'porta cerveja', 'porta litrao', 'porta latao', 'copo americano', 'copo desc', 'copo transp', 'palito', 'canudo', 'guardanapo', 'porta guardanapo', 'porta canudo', 'baralho', 'abridor', 'isqueiro', 'gelo'],
        exclude: ['doce', 'pilha', 'bala'],
        minSize: 0,
      },
    ],
  },
  {
    id: 'delivery',
    name: 'Delivery e embalagens',
    note: 'Embalagens para preparo, entrega e viagem',
    icon: 'truck',
    groups: [
      {
        name: 'Marmitex e bandejas',
        categories: ['eps (isopor)/bandejas aluminio'],
        keywords: ['marmitex', 'marmita', 'bandeja', 'assadeira', 'pote termico', 'copo termico', 'tampa pote'],
        exclude: ['disco pizza', 'hambur', 'prato', 'frigideira', 'panela', 'canecao', 'caneca', 'leiteira', 'cuscuzeira', 'chaleira', 'caçarola', 'cacarola', 'forma de', 'isqueiro'],
        minSize: 0,
      },
      {
        name: 'Potes, garrafas e tampas',
        categories: [],
        keywords: ['pote', 'emb kit pot', 'sushi', 'emb. ret', 'embalagem (base)', 'embalagem (tampa)', 'frangueira', 'garrafa quadrada', 'garrafa cristal'],
        exclude: ['choco', 'pacoca', 'doce', 'bala', 'goma', 'confeito', 'granulado', 'cond ', 'escova', 'soda', 'marmitex', 'termico', 'brinq', 'slime', 'chicle', 'pir '],
        minSize: 0,
      },
      {
        name: 'Pizza',
        categories: [],
        keywords: ['pizza', 'disco pizza'],
        exclude: ['far trigo', 'molho'],
        minSize: 0,
      },
      {
        name: 'Hambúrguer e lanches',
        categories: [],
        keywords: ['hambur', 'hot dog', 'papel p/hamburg', 'embalagem batata', 'emb batata', 'papel acoplado'],
        exclude: ['molho'],
        minSize: 0,
      },
      {
        name: 'Sacolas de entrega',
        categories: [],
        keywords: ['deliv', 'kraft', 'sacola papel', 'sacola camis', 'sacola p/', 'sacola cam'],
        exclude: ['talher', 'teste', 'pipoca', 'chup'],
        minSize: 0,
      },
      {
        name: 'Copos e tampas',
        categories: [],
        keywords: ['copo ', 'tampa copo', 'tampa t', 'tampa bolha', 'tampa p/ copo'],
        exclude: ['doce', 'bala', 'choco', 'extrato', 'americano', 'nadir', 'pote', 'marmitex', 'termico', 'azeitona', 'agua', 'frigideira', 'panela', 'canecao', 'caneca', 'leiteira', 'cuscuzeira', 'chaleira', 'caçarola', 'cacarola', 'forma de', 'isqueiro'],
        minSize: 0,
      },
      {
        name: 'Sachês e molhos individuais',
        categories: [],
        keywords: ['sache'],
        exclude: ['canudo', 'garfo', 'faca', 'colher', 'sabao', 'amaciante', 'detergente', 'milho', 'ervilha'],
        minSize: 0,
      },
      {
        name: 'Talheres e guardanapos',
        categories: [],
        keywords: ['garfo', 'faca', 'colher', 'talher', 'guardanapo', 'canudo', 'mexedor'],
        exclude: ['porta'],
        minSize: 0,
      },
      {
        name: 'Filme PVC e papel alumínio',
        categories: ['filme pvc/ papel aluminio'],
        keywords: [],
        exclude: [],
        minSize: 0,
      },
    ],
  },
  {
    id: 'higiene',
    name: 'Perfumarias e higiene',
    note: 'Higiene pessoal e cuidados',
    icon: 'medkit',
    groups: [
      {
        name: 'Higiene pessoal',
        categories: ['higiene pessoal'],
        keywords: [],
        exclude: ['papel hig', 'fralda', 'creme dental', 'escova dental', 'escova dent', 'fio dental', 'enxaguante', 'lava roupas', 'limp. perf', 'papel interf', 'papel toalha', 'escolva'],
        minSize: 0,
      },
      {
        name: 'Papel higiênico e fraldas',
        categories: [],
        keywords: ['papel hig', 'fralda', 'lenco umedec'],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Higiene bucal',
        categories: [],
        keywords: ['creme dental', 'escova dental', 'escova dent', 'escolva', 'fio dental', 'enxaguante'],
        exclude: [],
        minSize: 0,
      },
    ],
  },
  {
    id: 'limpeza',
    name: 'Limpeza profissional',
    note: 'Produtos e utensílios de limpeza',
    icon: 'spray',
    groups: [
      {
        name: 'Produtos de limpeza',
        categories: ['limpeza'],
        keywords: ['lava roupas', 'limp. perf'],
        exclude: ['vassoura', 'rodo', 'pano', 'esponja', 'luva', 'saco lixo'],
        minSize: 0,
      },
      {
        name: 'Vassouras, rodos e utensílios',
        categories: [],
        keywords: ['vassoura', 'rodo', 'rastelo', 'pa p/', 'pa para', 'pa s/cabo', 'pa (s/cabo)', 'pa de lixo', 'cabo madeira', 'escova', 'saco p/lixo', 'desentupidor', 'balde', 'lixeira', 'esfregao', 'mop'],
        exclude: ['escova dental', 'escova dent'],
        minSize: 0,
      },
      {
        name: 'Panos, esponjas e luvas',
        categories: [],
        keywords: ['pano', 'esponja', 'flanela', 'luva', 'la de aco', 'bombril'],
        exclude: ['nitrilica', 'vinil', 'descartavel', 'latex', 'plast'],
        minSize: 0,
      },
      {
        name: 'Sacos de lixo',
        categories: [],
        keywords: ['saco lixo', 'saco de lixo'],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Papel toalha e dispensers',
        categories: [],
        keywords: ['papel toalha', 'papel interf', 'dispenser', 'papel hig'],
        exclude: [],
        minSize: 0,
      },
    ],
  },
  {
    id: 'utilidades',
    name: 'Utilidades e bazar',
    note: 'Utensílios e itens para o dia a dia',
    icon: 'grid',
    groups: [
      {
        name: 'Utilidades domésticas',
        categories: ['utilidades'],
        keywords: [],
        exclude: ['vassoura', 'rodo', 'rastelo', 'saco lixo', 'saco p/lixo', 'esponja', 'pano', 'pa p/', 'pa para', 'pa s/cabo', 'pa (s/cabo)', 'p/lixo', 'cabo madeira', 'papel toalha', 'escova', 'esfregao', 'flanela'],
        minSize: 0,
      },
      {
        name: 'Filme PVC e papel alumínio',
        categories: ['filme pvc/ papel aluminio'],
        keywords: [],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Fogos e festas',
        categories: ['fogos'],
        keywords: ['vela', 'balao'],
        exclude: [],
        minSize: 0,
      },
    ],
  },
  {
    id: 'pizzarias',
    name: 'Pizzarias',
    note: 'Massa, recheios, embalagens e bebidas',
    icon: 'pizza',
    groups: [
      {
        name: 'Massa: farinhas e fermentos',
        categories: ['dona benta'],
        keywords: ['far trigo', 'fermento', 'fermix', 'farinha rosca', 'semolina', 'fuba'],
        exclude: ['c/ferm', 'bolo'],
        minSize: 450,
      },
      {
        name: 'Molhos e recheios',
        categories: [],
        keywords: ['molho tomate', 'molho de tomate', 'molho pizza', 'ajuda pizza', 'extrato', 'polpa tomate', 'azeitona', 'palmito', 'milho verde', 'ervilha', 'cogumelo', 'oregano', 'azeite', 'calabresa', 'mortadela', 'bacon', 'catupiry', 'requeijao', 'presunto', 'atum', 'sardinha'],
        exclude: ['chips', 'salg', 'pipoca', 'gulao', 'gulossauros', 'sache', 'farofa', 'sorvete', 'bisc'],
        minSize: 900,
      },
      {
        name: 'Temperos e condimentos',
        categories: ['1.5-condimentos guarana', 'temperos'],
        keywords: ['caldo', 'tempero', 'cond ', 'sal refinado', 'sal grosso', 'amaciante de carne', 'creme de cebola', 'colorau', 'oregano', 'pimenta do reino', 'pimenta reino', 'alho frito'],
        exclude: ['sache', 'chips', 'pipoca', 'salg', 'bisc', 'bala', 'ag ', 'sab', 'sorvete', 'pote', 'doce', 'mini ', 'corante', 'doce leite', 'doce de leite', 'bolinho', 'chantil', 'cobertura', 'granulado', 'confeit', 'mistura p/ bolo', 'mistura bolo', 'creme de conf', 'sob.lactea', 'glucose', 'choco', 'gelatina', 'aroma', 'essencia', 'leite po', 'recheio', 'forneavel', 'goiabada', 'coco ralado', 'fermento', 'reforcador', 'melhorador', 'mist. prep', 'bicarbonato', 'sal amoniaco', 'caldo de cana'],
        minSize: 200,
      },
      {
        name: 'Embalagens de pizza',
        categories: [],
        keywords: ['pizza', 'disco pizza', 'sacola p/pizza'],
        exclude: ['far trigo', 'molho'],
        minSize: 0,
      },
      {
        name: 'Sachês e molhos individuais',
        categories: [],
        keywords: ['sache'],
        exclude: ['canudo', 'garfo', 'faca', 'colher', 'sabao', 'amaciante', 'detergente', 'milho', 'ervilha'],
        minSize: 0,
      },
      {
        name: 'Bebidas',
        categories: ['3.2-refrigerantes', '3.1-sucos', '3.4-agua mineral', '4.1-cervejas'],
        keywords: [],
        exclude: ['porta'],
        minSize: 0,
      },
      {
        name: 'Descartáveis e proteção',
        categories: [],
        keywords: ['guardanapo', 'luva', 'touca', 'garfo', 'faca', 'papel aluminio'],
        exclude: ['porta guardanapo'],
        minSize: 0,
      },
    ],
  },
  {
    id: 'hamburguerias',
    name: 'Hamburguerias e lanches',
    note: 'Molhos, embalagens e descartáveis',
    icon: 'fast-food',
    groups: [
      {
        name: 'Molhos food service',
        categories: [],
        keywords: ['maionese', 'catchup', 'mostarda', 'barbecue', 'molho cheddar', 'molho especial', 'molho verde', 'molho alho', 'molho hot dog', 'molho barbecue', 'molho shoyo', 'molho pimenta'],
        exclude: ['sache', 'pote'],
        minSize: 900,
      },
      {
        name: 'Sachês e molhos individuais',
        categories: [],
        keywords: ['sache'],
        exclude: ['canudo', 'garfo', 'faca', 'colher', 'sabao', 'amaciante', 'detergente', 'milho', 'ervilha'],
        minSize: 0,
      },
      {
        name: 'Batata, bacon e acompanhamentos',
        categories: ['banhas'],
        keywords: ['batata palha', 'bacon', 'salsicha', 'banha', 'torresmo', 'cheddar', 'milho verde', 'ervilha'],
        exclude: ['chips', 'gulao', 'gulossauros', 'pipoca', 'doce', 'farofa', 'sache', 'sorvete', 'salg', ' ond ', 'molho'],
        minSize: 900,
      },
      {
        name: 'Embalagens de lanche',
        categories: [],
        keywords: ['hambur', 'hot dog', 'papel p/hamburg', 'emb batata', 'embalagem batata', 'sacola p/hamburg', 'papel acoplado'],
        exclude: ['molho'],
        minSize: 0,
      },
      {
        name: 'Sacolas de entrega',
        categories: [],
        keywords: ['deliv', 'kraft', 'sacola papel'],
        exclude: ['talher'],
        minSize: 0,
      },
      {
        name: 'Bebidas',
        categories: ['3.2-refrigerantes', '3.1-sucos', '3.3-energeticos', '3.4-agua mineral', '4.1-cervejas'],
        keywords: [],
        exclude: ['porta'],
        minSize: 0,
      },
      {
        name: 'Descartáveis e proteção',
        categories: [],
        keywords: ['guardanapo', 'canudo', 'copo desc', 'copo transp', 'luva', 'touca', 'garfo', 'faca'],
        exclude: ['porta', 'borracha', 'latex'],
        minSize: 0,
      },
    ],
  },
  {
    id: 'sorveterias',
    name: 'Sorveterias e açaiterias',
    note: 'Bases, coberturas, copos e colheres',
    icon: 'ice-cream',
    groups: [
      {
        name: 'Bases e pós para sorvete',
        categories: [],
        keywords: ['po  p/sorvete', 'po p/sorvete', 'sorvete', 'acai', 'liga neutra', 'emulsificante', 'saborizante'],
        exclude: ['doce mole', 'banana fit', 'mariola', 'ref ', 'pazinha', 'colher'],
        minSize: 0,
      },
      {
        name: 'Coberturas e complementos',
        categories: [],
        keywords: ['cobertura', 'granulado', 'confeit', 'leite cond', 'leite condensado', 'pacoca', 'amendoim', 'choco creme', 'creme de avela', 'coco ralado', 'calda', 'sob.lactea', 'marshmallow', 'chocoball', 'choco bolinha', 'ovomaltine', 'gotas'],
        exclude: ['bala', 'mendoreto', 'dori 70g', 'pirulito', 'pir ', 'japones', 'salgado', 'coquetel', 'amassyxup', 'barra', 'barrinha', 'brinq', 'sequilho', 'doce machado', 'bisc'],
        minSize: 0,
      },
      {
        name: 'Copos, potes e tampas',
        categories: [],
        keywords: ['copo ', 'pote', 'tampa copo', 'tampa bolha', 'tampa t', 'tampa pote'],
        exclude: ['doce', 'bala', 'choco', 'pacoca', 'extrato', 'americano', 'nadir', 'marmitex', 'emb kit', 'goma', 'confeito', 'cond ', 'soda', 'escova', 'sushi', 'p/ molho', 'azeitona', 'agua', 'brinq', 'slime', 'chicle', 'pir ', 'frigideira', 'panela', 'canecao', 'caneca', 'leiteira', 'cuscuzeira', 'chaleira', 'caçarola', 'cacarola', 'forma de', 'isqueiro'],
        minSize: 0,
      },
      {
        name: 'Colheres, canudos e guardanapos',
        categories: [],
        keywords: ['colher', 'canudo', 'guardanapo', 'mexedor', 'pazinha'],
        exclude: ['porta'],
        minSize: 0,
      },
      {
        name: 'Bebidas',
        categories: ['3.2-refrigerantes', '3.1-sucos', '3.4-agua mineral'],
        keywords: [],
        exclude: [],
        minSize: 0,
      },
    ],
  },
  {
    id: 'marmitarias',
    name: 'Marmitarias e restaurantes a quilo',
    note: 'Cozinha em volume e embalagens',
    icon: 'soup',
    groups: [
      {
        name: 'Molhos food service',
        categories: [],
        keywords: ['maionese', 'catchup', 'mostarda', 'molho', 'barbecue', 'shoyu', 'extrato', 'polpa tomate', 'vinagre'],
        exclude: ['sache', 'chips', 'pipoca', 'salg', 'bisc', 'bala', 'ag ', 'sab', 'sorvete', 'pote', 'doce', 'mini ', 'corante', 'doce leite', 'doce de leite', 'bolinho', 'chantil', 'cobertura', 'granulado', 'confeit', 'mistura p/ bolo', 'mistura bolo', 'creme de conf', 'sob.lactea', 'glucose', 'choco', 'gelatina', 'aroma', 'essencia', 'leite po', 'recheio', 'forneavel', 'goiabada', 'coco ralado', 'fermento', 'reforcador', 'melhorador', 'mist. prep'],
        minSize: 700,
      },
      {
        name: 'Temperos e condimentos',
        categories: ['1.5-condimentos guarana', 'temperos'],
        keywords: ['caldo', 'tempero', 'cond ', 'sal refinado', 'sal grosso', 'amaciante de carne', 'creme de cebola', 'colorau', 'oregano', 'pimenta do reino', 'pimenta reino', 'alho frito'],
        exclude: ['sache', 'chips', 'pipoca', 'salg', 'bisc', 'bala', 'ag ', 'sab', 'sorvete', 'pote', 'doce', 'mini ', 'corante', 'doce leite', 'doce de leite', 'bolinho', 'chantil', 'cobertura', 'granulado', 'confeit', 'mistura p/ bolo', 'mistura bolo', 'creme de conf', 'sob.lactea', 'glucose', 'choco', 'gelatina', 'aroma', 'essencia', 'leite po', 'recheio', 'forneavel', 'goiabada', 'coco ralado', 'fermento', 'reforcador', 'melhorador', 'mist. prep', 'bicarbonato', 'sal amoniaco', 'caldo de cana'],
        minSize: 200,
      },
      {
        name: 'Óleos, gorduras e conservas',
        categories: ['banhas'],
        keywords: ['oleo', 'azeite', 'banha', 'gordura', 'gordurina', 'margarina', 'azeitona', 'palmito', 'milho verde', 'ervilha', 'seleta', 'cogumelo', 'champignon', 'pepino', 'pimenta biquinho', 'tomate seco', 'cebolinha', 'alcaparra', 'atum', 'sardinha', 'conserva'],
        exclude: ['sache', 'chips', 'pipoca', 'salg', 'bisc', 'bala', 'ag ', 'sab', 'sorvete', 'pote', 'doce', 'mini ', 'corante', 'doce leite', 'doce de leite', 'bolinho', 'chantil', 'cobertura', 'granulado', 'confeit', 'mistura p/ bolo', 'mistura bolo', 'creme de conf', 'sob.lactea', 'glucose', 'choco', 'gelatina', 'aroma', 'essencia', 'leite po', 'recheio', 'forneavel', 'goiabada', 'coco ralado', 'fermento', 'reforcador', 'melhorador', 'mist. prep'],
        minSize: 900,
      },
      {
        name: 'Farinhas, massas e grãos',
        categories: [],
        keywords: ['far trigo', 'farinha', 'farofa', 'polvilho', 'fecula', 'amido', 'arroz', 'feijao', 'fuba', 'trigo para kibe', 'trigo p', 'batata palha', 'mist. prep. pao de queijo', 'macarrao', 'espaguete', 'massa', 'batata em flocos', 'pure'],
        exclude: ['sache', 'chips', 'pipoca', 'salg', 'bisc', 'bala', 'ag ', 'sab', 'sorvete', 'pote', 'doce', 'mini ', 'aveia', 'kimilho', 'mistura p/ bolo', 'mistura bolo', 'creme de conf', 'massa corrida'],
        minSize: 900,
      },
      {
        name: 'Marmitex e bandejas',
        categories: ['eps (isopor)/bandejas aluminio'],
        keywords: ['marmitex', 'marmita', 'bandeja', 'assadeira', 'pote termico', 'copo termico', 'tampa pote'],
        exclude: ['disco pizza', 'hambur', 'prato', 'frigideira', 'panela', 'canecao', 'caneca', 'leiteira', 'cuscuzeira', 'chaleira', 'caçarola', 'cacarola', 'forma de', 'isqueiro'],
        minSize: 0,
      },
      {
        name: 'Filme e papel alumínio',
        categories: ['filme pvc/ papel aluminio'],
        keywords: [],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Sachês e molhos individuais',
        categories: [],
        keywords: ['sache'],
        exclude: ['canudo', 'garfo', 'faca', 'colher', 'sabao', 'amaciante', 'detergente', 'milho', 'ervilha'],
        minSize: 0,
      },
      {
        name: 'Talheres e descartáveis',
        categories: [],
        keywords: ['garfo', 'faca', 'colher', 'talher', 'guardanapo', 'copo desc', 'copo transp'],
        exclude: ['porta'],
        minSize: 0,
      },
      {
        name: 'Sacolas',
        categories: [],
        keywords: ['sacola camis', 'sacola cam', 'sacola p/', 'deliv', 'kraft'],
        exclude: ['teste', 'hambur', 'pipoca', 'chup'],
        minSize: 0,
      },
      {
        name: 'Bebidas',
        categories: ['3.2-refrigerantes', '3.1-sucos', '3.4-agua mineral'],
        keywords: [],
        exclude: [],
        minSize: 0,
      },
      {
        name: 'Luvas, toucas e proteção',
        categories: [],
        keywords: ['luva', 'touca', 'mascara', 'avental'],
        exclude: [],
        minSize: 0,
      },
    ],
  },
];
